---
title: Maak een nieuwe achtergrond in de Paint-editor
hero_image: images/banner.png
description: Maak een nieuwe achtergrond in de Paint-editor
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Maak een nieuwe achtergrond in de Paint-editor
