---
title: Teken een nieuwe achtergrond
hero_image: images/banner.png
description: Teken een nieuwe achtergrond
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Inleiding
