title: Create a new backdrop in the Paint editor
hero_image: images/banner.png
description: Create a new backdrop in the Paint editor
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Create a new backdrop in the Paint editor
