---
title: Crie um novo cenário no editor do Paint
hero_image: images/banner.png
description: Crie um novo cenário no editor do Paint
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Crie um novo cenário no editor do Paint
