---
title: Crea un nuevo fondo en el Editor de dibujo
hero_image: images/banner.png
description: Crea un nuevo fondo en el Editor de dibujo
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Crea un nuevo fondo en el Editor de dibujo
