---
title: Pintar un nuevo fondo
hero_image: images/banner.png
description: Pintar un nuevo fondo
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Introducción
