---
title: Utwórz nowe tło w edytorze Malowania
hero_image: images/banner.png
description: Utwórz nowe tło w edytorze Paint
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Utwórz nowe tło w edytorze Paint
