---
title: Skapa en ny bakgrund i målarredigeraren
hero_image: images/banner.png
description: Skapa en ny bakgrund i målarredigeraren
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Skapa en ny bakgrund i målarredigeraren
