---
title: Peindre un nouvel arrière-plan
hero_image: images/banner.png
description: Peindre un nouvel arrière-plan
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Introduction
