---
title: Créer un nouvel arrière-plan dans l'éditeur de peinture
hero_image: images/banner.png
description: Créer un nouvel arrière-plan dans l'éditeur de peinture
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Créer un nouvel arrière-plan dans l'éditeur de peinture
