---
title: Crea un nuovo sfondo nell'editor di Paint
hero_image: images/banner.png
description: Crea un nuovo sfondo nell'editor di Paint
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Crea un nuovo sfondo nell'editor di Paint
